# -*- coding: utf-8 -*-
"""Python Programming DAY 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nSSSqgjT9cx-CiRnQON54t3OXZ7JCSt
"""

a = 10
b = 20

a+b

a-b

print("Multiplication: ",a*b)

a/b

a//b

# Variables
a = 10
b = 4

#Addition
print("Addition: ",a+b)

#Subtraction
print("Subtraction: ",a-b)

#Multiplication
print("Multiplication: ",a*b)

#Division
print("Division: ",a/b)

distance = 7425
speed = 550
time = distance/speed
print(time)

x = 50
tip = x*20/100
print("tip: ",tip)

x = 50
tip = x*40/100
print("tip: ",tip)

x = 125
tip = x*20/100
print("tip: ",tip)

x = 1024
tip = x*20/100
print("tip: ",tip)

x = 200
tip = x*20/1000
print(tip)

"""Different Operators"""

a = 10
b = 20

print(a > b)
print(a < b)
print(a == b)
print(a != b)
print(a >= b)
print(a <= b)

a = 30
b = 20

print(a > b)
print(a < b)
print(a == b)
print(a != b)
print(a >= b)
print(a <= b)

a = 10
b = -5

print(a > b)
print(a < b)
print(a == b)
print(a != b)
print(a >= b)
print(a <= b)

a = 0
b = -5

print(a > b, a < b, a == b, a != b, a >= b, a <= b)

a = True
b = False
print(a and b)
print(a or b)
print(not a)

a = 10
b = a
print(b)

b+=a
print(b)
b-=a
print(b)
b*=a
print(b)
b<<=a
print(b)

a = 10
b = 20
c = a

print(a is not b)
print(a is c)
print(b is c)

x = 10
y = 15
list = [10, 20, 30, 40, 50]

if(x not in list):
  print("x is NOT present in the given list.")
else:
  print("x is present in the given list.")
if(y in list):
  print("y is present in the list.")
else:
  print("y is NOT present in the given list.")

x = 18
y = 20
list = [10, 20, 30, 40, 50]

if(x not in list):
  print("x is NOT present in the given list.")
else:
  print("x is present in the given list.")
if(y in list):
  print("y is present in the list.")
else:
  print("y is NOT present in the given list.")

(1, 2, 3) + (4, 5, 6)

[1, 2, 3] + [4, 5, 6]

"Hello" + " " + "World!!"

(1, 2, 3) * 2

"World!!" * 3

"""Conditional Statements"""

age = 16
if (age < 18):
  print("You can't vote.")
else:
  print("You can vote.")

age = 19
if (age < 18):
  print("You can't vote.")
else:
  print("You can vote.")

age = 20
print("You can't vote.") if age < 18 else print("You can vote.")

age = 12
print("You can't vote.") if age < 18 else print("You can vote.")
print("Done!!")

x = 35
if x > 20:
  print("Above twenty")
  if x > 30:
    print("Above thirty")
  else:
    print("Below thirty but above 20")
else:
  print("Below twenty")

x = 25
if x > 20:
  print("Above twenty")
  if x > 30:
    print("Above thirty")
  else:
    print("Below thirty but above 20")
else:
  print("Below twenty")

x = 25
if x > 20:
  print("Above twenty")
  if x > 30:
    print("Above thirty")
  else:
    print("Below thirty but above 20")
else:
  print("Below twenty")

a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a = 33
b = 33
if b > a: print("b is greater than a")
elif a == b: print("a and b are equal")

a = 33
b = 34
if b > a: print("b is greater than a")
elif a == b: print("a and b are equal")

a = 33
b = 50
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("b is less than a")

a = 70
b = 50
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("b is less than a")

a = 70
b = 50
if b > a: print("b is greater than a")
elif a == b: print("a and b are equal")
else: print("b is less than a")

a = int(input("enter a value "))
b = int(input("enter b value "))
if b > a: print("b is greater than a")
elif a == b: print("a and b are equal")
else: print("b is less than a")

num = int(input("Enter a number: "))
if num % 2 == 0:
  print("Even Number")

else:
  print("Odd Number")

num = int(input("Enter a number: "))
if num % 2 == 0:
  print("Even Number")

else:
  print("Odd Number")

weight = int(input("Enter weight: "))
height = float(input("Enter height: "))
x = weight/float(height*height)
if x < 18.5:
  print("Underweight")
elif x >= 18.5 and x < 25:
  print("Normal")
elif x >= 25 and x < 30:
  print("Overweight")
else:
  print("Obesity")

weight = int(input("Enter weight: "))
height = float(input("Enter height: "))
x = weight/float(height*height)
if x < 18.5:
  print("Underweight")
elif x >= 18.5 and x < 25:
  print("Normal")
elif x >= 25 and x < 30:
  print("Overweight")
else:
  print("Obesity")

