# -*- coding: utf-8 -*-
"""Python Programming DAY 3 part 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TP42FrLFRWYebHluGPElnGqhu4LdSzK
"""

i = 1
while i < 8:
  print(i)
  i += 1

i = 1
while i < 8:
  print(i)
  if i == 4:
    break
  i += 1

i = 1
while i < 9:
  print(i)
  if i == 5:
    break
  i += 1

i = 1
while i < 9:
  print(i)
  if i == 5:
    break
  i += 2

i = 10
while i > 1:
  print(i)
  if i == 3:
    break
  i -= 1

for number in [1, 2, 3, 5, 6, 10, 11, 12]:
  if number == 6:
    break
  print(number)

print('Bye')

i = 1
while i < 11:
   if i == 6:
    break
   print(i)
   i += 1

print('Go!')

for number in [1, 2, 3, 5, 6, 10, 11, 12]:
  if number == 6:
    continue
  print(number)

print('Bye')

i = 1
while i < 11:
   if i == 6:
    continue
   print(i)
   i += 1

print('Go!')



