# -*- coding: utf-8 -*-
"""Python Programming DAY 3 part 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jk7-DCPyk3pXwd2IOLczuGKBQ2_tElfq
"""

num = 12
for i in range(1, 11):
  print(num, 'x', i, '=', num*i)

num = 12
for i in range(2, 9):
  print(num, 'x', i, '=', num*i)

num = 320
print("The factors of", num, "are:", end=' ')
for i in range(1, num + 1):
  if num % i == 0:
    print(i, end=' ')

num = 320
factors = [i for i in range(1, num + 1) if num % i == 0]
print("The factors of", num, "are:", factors)

rows = 5
for i in range(1, rows + 1):
  for j in range(i):
    print("*", end=" ")
  print()

rows = 5
for i in range(1, rows + 1):
  for j in range(i):
    print("Aditi", end=" ")
  print()

rows = 5
for i in range(1, rows + 1):
  for j in range(i):
    print("#", end=" ")
  print()

for num in range(2, 21):
  is_prime = True
  for div in range(2, int(num ** 0.5) + 1):

def name():
  print("What's your name?")

name()

def my_name(name):
  print("My name is" + name)
my_name(' Aditi')

def my_name(name, clg, branch):
  print("My name is" + name)
  print("My college is" + clg)
  print("My branch is" + branch)
my_name(' Aditi', ' KGRCET', ' CSE AIML A')

def sum(a, b):
  return a+b
x = sum(5, 21)
print("The sum is", x)

def product(a, b):
  return a*b
x = product(5, 21)
print("The product is", x)

