# -*- coding: utf-8 -*-
"""Python Programming DAY 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SNB8hQaQK8ch6uVdpPALNxksI6OLCfd-
"""



print("Hello, World!!")

print(Hello, World!!)

print('Aditi Thakur')

print('''Aditi Thakur''')

print(5)

print(10%3)

print(35726474638474847447)

print('Hello World')
print('Hello KGRCET')
print('Welcome to Python Workshop')

name = input("Enter your name:")
print("Hello," + name)

roll_no = input("Enter your roll number:")
print("Hello," + roll_no)

_import=input("This is a import variable:")
print(_import)

name="hello"
print(@hello)

X=10
print(X)

x="Kgrcet"
print(x)

import keyword
print("The list of the keywords are:")
print(keyword.kwlist)

age = 18
print("I am " + str(age) + " years old.")

from re import A
a = 400
A = "KGRCET"
# A will not overwrite a
print(A)
print(a)

x = 5
y = "KGRCET"
print(x)
print(y)

x = 4
x = "Hello"
print(x)

x = "Python"
y = "is"
z = "awesome"
print(x, y, z)

x = "Python"
y = "is"
z = "awesome"
print(x + y + z)

x = 500
y = "KGRCET"
print(x + y)

x = "500"
y = "KGRCET"
print(x + y)

x, y = 2, 3
print(x)

y

x, y, z = 2, 3, 4
x
y
z

x

y

z



"""Swapping numbers"""

a = 10
b = 20
a, b = b, a

a

b

x, y = 2, 3

x

y

x, y = y, x

a = b = x = 2

a

b

x

x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)

x = y = z = "Orange"
print(x)
print(y)
print(z)



"""Casting"""

x = str(3)
y = int(3)
z = float(3)
print(x)
print(y)
print(z)

x = 5
y = "KGRCET"
print(type(x))
print(type(y))

print(x+y)



"""Scope of a variable"""

def my_function():
  local_var = "I am local."
  print(local_var)

my_function()
print(local_var)

global_var = 2

def my_function():
  print(global_var)

my_function()

a = []
a

b = 0
a = [1, 6, b, 9]

print(a)



"""Boolean"""

x = True

# Display x:
print(x)

# Display the data type of x:
print(type(x))

a = 5
print(type(a))
b = 5.0
print(type(b))
c = 2 + 5j
print(type(c))



"""string data type

"""

s = "Welcome to Python Workshop"
print(s)

# Check data type
print(type(s))

# Access string with index
print(s[1])
print(s[2])
print(s[-1])
print(s[0])
print(s[7])

s[0]

fruit = "watermelon"
print(fruit[3])

"""String Concatenation"""

string_1 = "I am studying in"
string_2 = " KGRCET"
print(string_1 + string_2)

year = " 1st year"
college = " KGRCET"
print("I am studying" + year + " in" + college)

"""String Replication"""

print("Aditi " * 5)

print("Oh Namah Shivaay!! " * 5)

"""List Data Type"""

# Empty list
a = []

# List with int values
a = [1, 2, 3]
print(a)

# List with mixed int and string
b = ["Aditi", "Hi!!", "Python", 4, 3]
print(b)

"""Accessing list"""

a = ["Python", 3, "is", "very", "easy"]
print("Accessing element from the list:")
print(a[0])
print(a[2])

print("Accessing element in negative indexing")
print(a[-1])
print(a[-3])

a = ["I", "am", "studying", "in", "KGRCET"]
print("Accessing element from the list:")
print(a[0])
print(a[2])

print("Accessing element in negative indexing")
print(a[-1])
print(a[-3])

"""Slice a list"""

a = [1, 2, 3, 4, 5]
a[0:3]

a[0:-1]

a[0:-2]



b = ["KGR", 1, 2, 3, 4]
b[2:4]

b = ["KGR", 1, 2, 3, 4]
b[-1:-2]

"""Sorting a list"""

alpha_list = [35, 45, 83, 48, 94]
alpha_list.sort()
print(alpha_list)

"""Add an item"""

fruit_list = ["apple", "banana", "orange"]
fruit_list.append("grapes")
print(fruit_list)

fruit_list2 = ["apple", "banana", "orange"]
fruit_list2.insert(1, "grapes")
print(fruit_list2)

fruit_list3 = ["apple", "banana", "orange"]
fruit_list3.insert(2, "grapes")
print(fruit_list3)

fruit_list4 = ["apple", "banana", "orange"]
fruit_list4.insert(0, "grapes")
print(fruit_list4)

numbers_list = [1, 2, 3, 5,]
numbers_list.append(4)
print(numbers_list)

"""Removing an item"""

fruit_list5 = ["apple", "banana", "orange"]
fruit_list5.remove("apple")
print(fruit_list5)

fruit_list6 = ["apple", "banana", "orange"]
fruit_list6.pop()
print(fruit_list6)

fruit_list7 = ["apple", "banana", "orange"]
del fruit_list7[1]
print(fruit_list7)



"""Operators"""

